### PR TITLE
Fix to global plots

### LINKED ISSUE #144: Global elipse projections not compatible with central_longitude argument
https://github.com/SCECcode/pycsep/blob/f8f75a99431928b25a98f3585fba9ca04fda466e/examples/tutorials/plot_customizations.py#L120

Robinson (Ellipse) projections for global forecasts are not working when central_longitude is passed as argument. This is due to cartopy version update.

### PR DESCRIPTION
**Pull request by pabloitu**
Fixes #144. Modified plot_spatial_dataset and plot_catalog to correctly handle Global plots. Updated plot_customizations example in the docs.

## Type of change:

- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Documentation update (this pull request adds no new code)

## Checklist:

- [* ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings   ### New versions of cartopy raises deprecation warning in shapely

### CODE REVIEW

**Comment by pabloitu** [comment]
build is failing because of obspy apparently

**Comment by wsavran** [comment]
interesting. i just merged 2 prs today and didn't run into this issue. all builds were successful. any idea why it might be failing?

**Comment by wsavran** [comment]
https://github.com/obspy/obspy/issues/2651
https://github.com/obspy/obspy/issues/2654

these issues were supposedly fixed in the latest obspy release. it has to do with numpy dependencies it looks like.

**Comment by wsavran** [comment]
https://github.com/SCECcode/pycsep/runs/4098858335?check_suite_focus=true here is an example of a successful build.

**Comment by pabloitu** [comment]
> https://github.com/SCECcode/pycsep/runs/4098858335?check_suite_focus=true here is an example of a successful build.

It failed too by now, like if there was some change in dependencies within those 3 hour difference in between Merges. I will try to check it, but should not be a problem of this PR, since the changes were minimum.

**Comment by pabloitu** [comment]
> [obspy/obspy#2651](https://github.com/obspy/obspy/issues/2651) [obspy/obspy#2654](https://github.com/obspy/obspy/issues/2654)
> 
> these issues were supposedly fixed in the latest obspy release. it has to do with numpy dependencies it looks like.

Did not read this, but arrived to the exact same conclusion. It was fixed, but for some reason our CI its getting a different `obs/setup.py`, where the line `from distutils.errors import DistutilsSetupError` is causing the error. In the pypi release  this was changed fixed as you mention.
If I repeat the CI steps on my local machine and using pip to install python dependencies it works well. But don't get why our CI is using a different method to install dependencies.

**Comment by wsavran** [comment]
yeah i dont think we are seeing the same issue. in the past we had to pin numpy to 1.18.1 to solve this issue. it almost seems like there was some type of issue with the ci runner itself. im trying again to see if the problem was transient. i dont feel comfortable merging this until the ci issues are resolved.

**Comment by pabloitu** [comment]
agreed.

**Comment by wsavran** [comment]
see this issue https://github.com/pypa/setuptools/issues/2849.

**Comment by wsavran** [comment]
@pabloitu pr looks good, will merge this after release of v.0.5.0. ill make a new release v0.5.1 with this change included.

**Review by wsavran — APPROVED** [review]

**Pull request merged**
